name: Deploy Zola site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Zola
        run: |
          curl -s https://api.github.com/repos/getzola/zola/releases/latest \
          | grep "browser_download_url.*zola.*x86_64-unknown-linux-gnu.tar.gz" \
          | cut -d '"' -f 4 | wget -i -
          tar -xzf zola*.tar.gz
          sudo mv zola /usr/local/bin/
      - name: Build site
        run: zola build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
